### ISSUE TITLE
anti-phase does not allow players to pass through nether portal blocks

### ISSUE THREAD

**Issue by roastnewt** [Sudzzy/FBasics#20]
Nether portal blocks should be passable

Running Fbasics version 1.5.0-SNAPSHOT (from here: https://github.com/Sudzzy/FBasics/tree/master/FBasics/target/)

Spigot version 1.7.10

**Comment by Sudzzy** [comment]
Really simple fix -- add PORTAL to the "hollow-materials" https://github.com/Sudzzy/FBasics/commit/6ee188ad351174dbb75c9b1230ee3902797353f6
