### ISSUE TITLE
Custom FBasics prefixes

### ISSUE THREAD

**Issue by scriptinator** [Sudzzy/FBasics#23]
I have seen a lot of servers with custom fbasics prefixes. The only one I can find right now is OriginMC though. I can not seem to find how to change the prefix. The one in the config only changes the crate message. I can't seem find it in the source code. How do you change the fbasics prefix or where in the source is it? Here is an example of a prefix:
![screen shot 2015-08-10 at 6 23 08 pm](https://cloud.githubusercontent.com/assets/6655672/9188095/1c632c50-3f8d-11e5-903d-1034ba8d8bde.png)

**Comment by Sudzzy** [comment]
It's in languages.yml

**Comment by scriptinator** [comment]
Thanks
