### ISSUE TITLE
Build Height.

### ISSUE THREAD

**Issue by Curtis3321** [Sudzzy/FBasics#28]
I've had to pretty much disable the Anti-Phase part of this plugin.

People are no longer able to head to world-height in an attempt to generate their factions walls. 

Is there any alternative rather than preventing them and pushing them down?

**Comment by Sudzzy** [comment]
There was a bug a little while ago which was fixed here: https://github.com/Sudzzy/FBasics/commit/a3a311f81e8bad970c6374a78f6af89ed8c9294d

Latest version of FBasics released right now is 2.1.1, what version are you running?
