### ISSUE TITLE
Console SPAM - 1000 lines - FBASICS

### ISSUE THREAD

**Issue by NickFirenzo** [Sudzzy/FBasics#31]
Hi,
I want to report a WARNs of fbasics plugin. In my console I getting more then 1000 lines with same text, pastebin: http://pastebin.com/DjURPsv0

After 15 minutis my server Shutting down, error: Broken Pipe

**Comment by Sudzzy** [comment]
Should be fixed here: https://github.com/Sudzzy/FBasics/commit/cf3440fa116dd63102a23328b5e299110d25e5bc
