### ISSUE TITLE
Using nether portal to teleport results in player ending up in a different location

### ISSUE THREAD

**Issue by RoboMWM** [Sudzzy/FBasics#35]
I didn't find out exactly where they are teleported, but I don't end up in the portal when teleporting to the nether. Seems to be a 1.9/1.9.2-specific bug.

If you can't reproduce, I'll re-test and get more specific results.

Not using factions, etc.

**Comment by RoboMWM** [comment]
https://www.spigotmc.org/threads/glitching-nether-portals-1-9.139002/ seems to be related.

**Comment by BrobReborn** [comment]
I just disabled antiglitch-phase (As RoboVM suggested) and it works fine now.

**Comment by Sudzzy** [comment]
Thanks, I'll look into this issue tomorrow. Apologies about the slow response time, I've been away on holiday and am in the airport to go home now. :)

**Comment by Sudzzy** [comment]
Fixed this a while ago, forgot to update this issue. Relevant commit: https://github.com/Sudzzy/FBasics/commit/2d4739eea40a6c6cf98eeb277b1840bdd33d6f1b
