### ISSUE TITLE
Latest version on spigotmc and dev build is broke on TacoSpigot 1.8.8 (PaperSpigot fork)

### ISSUE THREAD

**Issue by CheatSupport** [Sudzzy/FBasics#41]
Download tacospigot here: https://ci.techcable.net/job/TacoSpigot-1.8.8/

Using FactionsUUID

**Comment by Sudzzy** [comment]
How exactly has it "broke"?

**Comment by CheatSupport** [comment]
not sure, just doesn't load. 2.1.6 works just fine. I think either 1.9 support broke it or something

**Comment by Sudzzy** [comment]
Using latest FBasics and latest TacoSpigot 1.8.8 (as linked) load and work fine as far as I can see.

**Comment by CheatSupport** [comment]
Hm thanks for the reply @Sudzzy, I'll give it another go.

**Comment by CheatSupport** [comment]
Still doesn't load. TacoSpigot 1.8.8 (paperspigot fork), when i do /pl FBasics just doesn't show up
