### ISSUE TITLE
Attacking horses triggers chest-dupe messages

### ISSUE THREAD

**Issue by Kanlaki101** [Sudzzy/FBasics#9]
If you mount a horse without accessing it's inventory, dismount, and attempt to attack it, the plugin triggers the "chest-dupe" error message. However, if you mount the horse and access it's inventory before attempting to attack it, everything works fine.

Spigot version: b73910a-aa92a45 (MC: 1.8)
FBasics version: 1.4.1 (from spigot website) - 1.4.0 (from plugin.yml)

**Comment by Sudzzy** [comment]
Fixed in latest build, thanks!
